language: go
go:
  - "1.10"
addons:
  apt:
    packages:
      - bc
      - jq
      - nodejs
      - wget
env:
  - FILEOUT="proxy_list_socks_all.txt"
install:
  - go get github.com/ericchiang/pup
script:
  - ./get_proxy_list.sh > $FILEOUT
  - sort -o $FILEOUT $FILEOUT && ex +'%!uniq' -scwq $FILEOUT && wc -l $FILEOUT
  - ./check_proxies.sh $FILEOUT
