language: go
go:
  - "1.10"
addons:
  apt:
    packages:
      - bc
      - jq
      - wget
install:
  - go get github.com/ericchiang/pup
script:
  - ./get_proxy_list.sh
after_script:
  - wc -l *.txt
